name: bayesian-models
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24
  - matplotlib=3.7  
  - scipy=1.10
  - ipywidgets=8.0
  - seaborn
  - ipympl               # 🔥 for `%matplotlib ipympl` to work
  - notebook             # for classic Jupyter (enables widgets)
  - jupyterlab  
