name: environment  # Change this to your preferred environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Adjust Python version if needed
  - numpy
  - matplotlib
  - scipy
  - ipywidgets
  - seaborn