name: bayesian-models
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools
  - jupyterlab
  - jags # Jags installation
  - pkg-config # pkg-config for pyjags installation
  - numpy=1.24
  - pip:
    - matplotlib==3.7
    - scipy==1.10
    - ipywidgets==8.0
    - seaborn
    - ipympl               # for `%matplotlib ipympl` to work
    - pyjags
